version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
    - "thenativeweb/wolkenkit-dev"
    default_assignees:
    - "goloroden"
    - "yeldiRium"
    default_labels:
    - "Dependencies"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
    allowed_updates:
    - match:
        dependency_type: "direct"
        update_type: "all"
    version_requirement_updates: "increase_versions"

  - package_manager: "docker"
    directory: "/docker/wolkenkit"
    update_schedule: "daily"
    default_reviewers:
    - "thenativeweb/wolkenkit-dev"
    default_assignees:
    - "goloroden"
    - "yeldiRium"
    default_labels:
    - "Dependencies"
    commit_message:
      prefix: "fix"

  - package_manager: "docker"
    directory: "/docker/wolkenkit-mariadb"
    update_schedule: "daily"
    default_reviewers:
    - "thenativeweb/wolkenkit-dev"
    default_assignees:
    - "goloroden"
    - "yeldiRium"
    default_labels:
    - "Dependencies"
    commit_message:
      prefix: "fix"

  - package_manager: "docker"
    directory: "/docker/wolkenkit-minio"
    update_schedule: "daily"
    default_reviewers:
    - "thenativeweb/wolkenkit-dev"
    default_assignees:
    - "goloroden"
    - "yeldiRium"
    default_labels:
    - "Dependencies"
    commit_message:
      prefix: "fix"

  - package_manager: "docker"
    directory: "/docker/wolkenkit-mongodb"
    update_schedule: "daily"
    default_reviewers:
    - "thenativeweb/wolkenkit-dev"
    default_assignees:
    - "goloroden"
    - "yeldiRium"
    default_labels:
    - "Dependencies"
    commit_message:
      prefix: "fix"

  - package_manager: "docker"
    directory: "/docker/wolkenkit-mysql"
    update_schedule: "daily"
    default_reviewers:
    - "thenativeweb/wolkenkit-dev"
    default_assignees:
    - "goloroden"
    - "yeldiRium"
    default_labels:
    - "Dependencies"
    commit_message:
      prefix: "fix"

  - package_manager: "docker"
    directory: "/docker/wolkenkit-postgres"
    update_schedule: "daily"
    default_reviewers:
    - "thenativeweb/wolkenkit-dev"
    default_assignees:
    - "goloroden"
    - "yeldiRium"
    default_labels:
    - "Dependencies"
    commit_message:
      prefix: "fix"

  - package_manager: "docker"
    directory: "/docker/wolkenkit-proxy"
    update_schedule: "daily"
    default_reviewers:
    - "thenativeweb/wolkenkit-dev"
    default_assignees:
    - "goloroden"
    - "yeldiRium"
    default_labels:
    - "Dependencies"
    commit_message:
      prefix: "fix"

  - package_manager: "docker"
    directory: "/docker/wolkenkit-redis"
    update_schedule: "daily"
    default_reviewers:
    - "thenativeweb/wolkenkit-dev"
    default_assignees:
    - "goloroden"
    - "yeldiRium"
    default_labels:
    - "Dependencies"
    commit_message:
      prefix: "fix"

  - package_manager: "docker"
    directory: "/docker/wolkenkit-sqlserver"
    update_schedule: "daily"
    default_reviewers:
    - "thenativeweb/wolkenkit-dev"
    default_assignees:
    - "goloroden"
    - "yeldiRium"
    default_labels:
    - "Dependencies"
    commit_message:
      prefix: "fix"
